parameters:

services:
    app.mailer:
        class: AppBundle\Services\Mailer
        arguments: ["@twig", "@mailer"]

    app.crawler:
        class: AppBundle\Services\Crawler

    app.mailer.producer: '@old_sound_rabbit_mq.mail_producer'