parameters:

services:

    app.mailer:
        class: AppBundle\Services\Mailer
        arguments: ["@twig", "@mailer"]

    app.crawler:
        class: AppBundle\Services\Crawler
        arguments: ["@em"]

    app.report.generator:
        class: AppBundle\Services\ReportGenerator

    # listeners
    app.before_action.listener:
        class: AppBundle\Listener\BeforeActionListener
        arguments: [ "@session", "@translator.default" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.exception_log.listener:
        class: AppBundle\Listener\ExceptionLogListener
        arguments: ["@enqueue.producer"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    # workers
    app.crawler.worker:
        class: 'AppBundle\Workers\CrawlerWorker'
        arguments: ["@app.crawler", "@em"]
        tags:
            - { name: 'enqueue.client.processor' }

    app.mailer.worker:
        class: AppBundle\Workers\MailerWorker
        arguments: ["@app.mailer"]
        tags:
            - { name: 'enqueue.client.processor' }

    # aliases
    em: '@doctrine.orm.default_entity_manager'

    #    _defaults:
    #        autowire: true
    #        autoconfigure: true
    #        public: false
    #
    #    AppBundle\:
    #        resource: '../../src/AppBundle/*'
    #        exclude: '../../src/AppBundle/{Entity,Migrations,Repository}'
    #
    #    AppBundle\Controller\:
    #        resource: '../../src/AppBundle/Controller'
    #        tags: ['controller.service_arguments']