parameters:

services:
    app.mailer:
        class: AppBundle\Services\Mailer
        arguments: ["@twig", "@mailer"]

    app.crawler:
        class: AppBundle\Services\Crawler
        arguments: ["@em"]

    app.feedback.listener:
        class: AppBundle\Listener\FeedbackListener
        arguments: ["@app.mailer.producer"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.exception_log.listener:
        class: AppBundle\Listener\ExceptionLogListener
        arguments: ["@app.mailer.producer"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.locale.listener:
        class: AppBundle\Listener\LocaleListener
        arguments: [ "@translator.default", "@session" ]
        tags:
           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.mailer.producer: '@old_sound_rabbit_mq.mail_producer'
    em: '@doctrine.orm.default_entity_manager'