parameters:

services:
    app.mailer:
        class: AppBundle\Services\Mailer
        arguments: ["@twig", "@mailer"]

    app.crawler:
        class: AppBundle\Services\Crawler
        arguments: ["@em"]

    # listeners
    app.before_action.listener:
        class: AppBundle\Listener\BeforeActionListener
        arguments: [ "@session", "@translator.default" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # workers
    app.crawler.worker:
        class: 'AppBundle\Workers\CrawlerWorker'
        arguments: ["@app.crawler", "@em"]
        tags:
            - { name: 'enqueue.client.processor' }

    app.mailer.worker:
        class: AppBundle\Workers\MailerWorker
        arguments: ["@app.mailer"]

    # aliases
    em: '@doctrine.orm.default_entity_manager'