parameters:

services:
    app.mailer:
        class: AppBundle\Services\Mailer
        arguments: ["@twig", "@mailer"]

    app.crawler:
        class: AppBundle\Services\Crawler
        arguments: ["@em"]

    # listeners
    app.exception_log.listener:
        class: AppBundle\Listener\ExceptionLogListener
        arguments: ["@app.mailer.producer"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.before_action.listener:
        class: AppBundle\Listener\BeforeActionListener
        arguments: [ "@session", "@translator.default" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # workers
    app.crawler.worker:
        class: AppBundle\Workers\CrawlerWorker
        arguments: ["@app.crawler", "@em"]

    app.mailer.worker:
        class: AppBundle\Workers\MailerWorker
        arguments: ["@app.mailer"]

    # aliases
    app.mailer.producer: '@old_sound_rabbit_mq.mail_producer'
    app.crawler.producer: '@old_sound_rabbit_mq.crawl_producer'
    em: '@doctrine.orm.default_entity_manager'
    redis: '@snc_redis.default'